/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.scoping;

import org.eclipse.xtext.mqrepl.scoping.AbstractModelQueryLanguageScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class ModelQueryLanguageScopeProvider extends AbstractModelQueryLanguageScopeProvider {
}
