/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.ide


/**
 * Use this class to register ide components.
 */
class ModelQueryLanguageIdeModule extends AbstractModelQueryLanguageIdeModule {
}
