/*
* generated by Xtext
*/
package org.eclipse.xtext.mqrepl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModelQueryLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/xtext/mqrepl/parser/antlr/internal/InternalModelQueryLanguage.tokens");
	}
}
