/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.xtext.mqrepl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.mqrepl.parser.antlr.internal.InternalModelQueryLanguageParser;
import org.eclipse.xtext.mqrepl.services.ModelQueryLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ModelQueryLanguageParser extends AbstractAntlrParser {

	@Inject
	private ModelQueryLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalModelQueryLanguageParser createParser(XtextTokenStream stream) {
		return new InternalModelQueryLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ModelQueryLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ModelQueryLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
