/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.validation;

import org.eclipse.xtext.mqrepl.validation.AbstractModelQueryLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelQueryLanguageValidator extends AbstractModelQueryLanguageValidator {
}
