/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.xtext.mqrepl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.mql.ui.internal.MqlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ModelQueryLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MqlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MqlActivator.getInstance().getInjector(MqlActivator.ORG_ECLIPSE_XTEXT_MQREPL_MODELQUERYLANGUAGE);
	}
	
}
