/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.mqrepl.ModelQueryLanguageRuntimeModule;
import org.eclipse.xtext.mqrepl.ModelQueryLanguageStandaloneSetup;
import org.eclipse.xtext.mqrepl.ide.ModelQueryLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ModelQueryLanguageIdeSetup extends ModelQueryLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    ModelQueryLanguageRuntimeModule _modelQueryLanguageRuntimeModule = new ModelQueryLanguageRuntimeModule();
    ModelQueryLanguageIdeModule _modelQueryLanguageIdeModule = new ModelQueryLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_modelQueryLanguageRuntimeModule, _modelQueryLanguageIdeModule));
  }
}
