/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.ide;

import org.eclipse.xtext.mqrepl.ide.AbstractModelQueryLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ModelQueryLanguageIdeModule extends AbstractModelQueryLanguageIdeModule {
}
