/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl;

import org.eclipse.xtext.mqrepl.ModelQueryLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ModelQueryLanguageStandaloneSetup extends ModelQueryLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new ModelQueryLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
