/*
 * generated by Xtext
 */
package org.eclipse.xtext.mqrepl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.mqrepl.ui.internal.ModelQueryLanguageActivator;
import org.eclipse.xtext.xbase.lib.Functions.Function0;
import org.osgi.framework.BundleContext;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModelQueryLanguageUiModule extends org.eclipse.xtext.mqrepl.ui.AbstractModelQueryLanguageUiModule {
	public ModelQueryLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	// contributed by org.eclipse.xtext.generator.types.TypesGeneratorFragment
	public java.lang.ClassLoader bindClassLoaderToInstance() {
		Function0<BundleContext> f = new Function0<BundleContext>() {

			@Override
			public BundleContext apply() {
				return ModelQueryLanguageActivator.getInstance().getBundle().getBundleContext();
			}
		};
		return new DelegatingClassLoader(f);
	}

}
