/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.mqrepl.ui.AbstractModelQueryLanguageUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelQueryLanguageUiModule extends AbstractModelQueryLanguageUiModule {
  public ModelQueryLanguageUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
