/**
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl.ui.contentassist;

import org.eclipse.xtext.mqrepl.ui.contentassist.AbstractModelQueryLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ModelQueryLanguageProposalProvider extends AbstractModelQueryLanguageProposalProvider {
}
