/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.xtext.mqrepl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractModelQueryLanguageScopeProvider extends XbaseBatchScopeProvider {
}
