/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.xtext.mqrepl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.mql.ui.internal.MqlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ModelQueryLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MqlActivator.getInstance().getInjector("org.eclipse.xtext.mqrepl.ModelQueryLanguage");
	}

}
