/**
 * generated by Xtext 2.11.0
 */
package org.eclipse.xtext.mqrepl.modelQueryLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.xtext.mqrepl.modelQueryLanguage.ModelQueryLanguagePackage
 * @generated
 */
public interface ModelQueryLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ModelQueryLanguageFactory eINSTANCE = org.eclipse.xtext.mqrepl.modelQueryLanguage.impl.ModelQueryLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>XMethod Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XMethod Declaration</em>'.
   * @generated
   */
  XMethodDeclaration createXMethodDeclaration();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ModelQueryLanguagePackage getModelQueryLanguagePackage();

} //ModelQueryLanguageFactory
