/*
 * generated by Xtext
 */
package org.eclipse.xtext.mqrepl;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.mqrepl.interpreter.ModelQueryLanguageInterpreter;
import org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("restriction")
public class ModelQueryLanguageRuntimeModule extends org.eclipse.xtext.mqrepl.AbstractModelQueryLanguageRuntimeModule {
	
	public Class<? extends XbaseInterpreter> bindXbaseInterpreter() {
		return ModelQueryLanguageInterpreter.class;
	}

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return ModelQueryLanguageValueConverterService.class;
	}
	
}
