/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package org.eclipse.xtext.mqrepl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelQueryLanguageStandaloneSetup extends ModelQueryLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelQueryLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
