grammar org.eclipse.xtext.mqrepl.ModelQueryLanguage with org.eclipse.xtext.xbase.Xbase

generate modelQueryLanguage "http://www.eclipse.org/xtext/mqrepl/ModelQueryLanguage"

import "http://www.eclipse.org/xtext/xbase/Xbase" as xbase

Model:
	imports = XImportSection
	body = XBlockExpressionWithoutBraces;

XBlockExpressionWithoutBraces returns xbase::XBlockExpression: 
	{xbase::XBlockExpression}
		(expressions+=XExpressionInsideBlock ';'?)*
	;	
