/*
* generated by Xtext
*/
package org.eclipse.xtext.mqrepl.ui.contentassist;

import org.eclipse.xtext.mqrepl.ui.contentassist.AbstractModelQueryLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ModelQueryLanguageProposalProvider extends AbstractModelQueryLanguageProposalProvider {

}
